// The Frame virtual-controller driver: two Quest 3 Touch Plus controllers beside
// the two the person holds, so an app that binds the Meta Quest 3 Touch profile
// sees them. A feeder writes poses and buttons into shared memory (vpen_shm.h);
// RunFrame polls it and reports haptics back.
// Cross-built on Windows for aarch64 SteamOS (build.sh) and for win64 (build-win.sh).
#ifdef __MINGW32__
#include "openvr_driver_mingw.h" // generated by build-win.sh
#else
#include "openvr_driver.h"
#endif
#include "vpen_shm.h"
#include "shm_compat.h"

#include <cstdio>
#include <cstring>

using namespace vr;

static const char *const kControllerType = "oculus_touch";
static const char *const kInputProfile = "{vpen}/input/vpen_profile.json";

static void log(const char *msg) {
	if (VRDriverLog())
		VRDriverLog()->Log(msg);
}

// One companion pen: a tracked device whose pose and trigger come from a shm slot.
class CPenDevice final : public ITrackedDeviceServerDriver {
public:
	CPenDevice(int slot, const vpen_shared *shm) : m_slot(slot), m_shm(shm) {
		std::snprintf(m_serial, sizeof(m_serial), "vpen_%d", slot);
	}

	EVRInitError Activate(uint32_t id) override {
		m_id = id;
		PropertyContainerHandle_t c = VRProperties()->TrackedDeviceToPropertyContainer(id);
		VRProperties()->SetStringProperty(c, Prop_ModelNumber_String, "vpen");
		VRProperties()->SetStringProperty(c, Prop_SerialNumber_String, m_serial);
		VRProperties()->SetStringProperty(c, Prop_ControllerType_String, kControllerType);
		VRProperties()->SetStringProperty(c, Prop_InputProfilePath_String, kInputProfile);
		VRProperties()->SetInt32Property(c, Prop_DeviceClass_Int32, TrackedDeviceClass_Controller);
		VRProperties()->SetInt32Property(c, Prop_ControllerRoleHint_Int32,
				m_slot == 0 ? TrackedControllerRole_LeftHand : TrackedControllerRole_RightHand);
		VRProperties()->SetInt32Property(c, Prop_ControllerHandSelectionPriority_Int32, -1000);
		VRProperties()->SetBoolProperty(c, Prop_NeverTracked_Bool, false);

		VRDriverInput()->CreateScalarComponent(c, "/input/trigger/value", &m_trigger,
				VRScalarType_Absolute, VRScalarUnits_NormalizedOneSided);
		VRDriverInput()->CreateScalarComponent(c, "/input/grip/value", &m_grip,
				VRScalarType_Absolute, VRScalarUnits_NormalizedOneSided);
		VRDriverInput()->CreateBooleanComponent(c, "/input/trigger/click", &m_trigger_click);
		VRDriverInput()->CreateBooleanComponent(c, "/input/grip/click", &m_grip_click);
		VRDriverInput()->CreateBooleanComponent(c, "/input/menu/click", &m_menu);
		VRDriverInput()->CreateBooleanComponent(c, "/input/system/click", &m_system);
		VRDriverInput()->CreateHapticComponent(c, "/output/haptic", &m_haptic);
		return VRInitError_None;
	}

	void Deactivate() override { m_id = k_unTrackedDeviceIndexInvalid; }
	void EnterStandby() override {}
	void *GetComponent(const char *) override { return nullptr; }
	void DebugRequest(const char *, char *buf, uint32_t size) override {
		if (size)
			buf[0] = 0;
	}

	DriverPose_t Pose() const {
		DriverPose_t p = {};
		p.qWorldFromDriverRotation.w = 1;
		p.qDriverFromHeadRotation.w = 1;
		p.deviceIsConnected = true;
		p.poseIsValid = true;
		p.result = TrackingResult_Running_OK;
		// Static fallback so the pen enumerates as a connected tracker before any
		// feeder exists: a small fan in front of the origin, one step per slot.
		p.vecPosition[0] = -0.3 + 0.2 * m_slot;
		p.vecPosition[1] = 1.2;
		p.vecPosition[2] = -0.4;
		p.qRotation.w = 1;
		if (m_shm && m_slot < (int)m_shm->count) {
			const vpen_pen &s = m_shm->pen[m_slot];
			p.vecPosition[0] = s.px;
			p.vecPosition[1] = s.py;
			p.vecPosition[2] = s.pz;
			p.qRotation.w = s.qw;
			p.qRotation.x = s.qx;
			p.qRotation.y = s.qy;
			p.qRotation.z = s.qz;
		}
		return p;
	}

#ifdef __MINGW32__
	// vrserver returns the struct MSVC-style: this, then the result pointer, which it expects back.
	DriverPose_t *GetPose(DriverPose_t *out) override {
		*out = Pose();
		return out;
	}
#else
	DriverPose_t GetPose() override { return Pose(); }
#endif

	// Called by the provider each frame with a stable copy of this slot.
	void Update(const vpen_pen &s, bool active) {
		if (m_id == k_unTrackedDeviceIndexInvalid)
			return;
		DriverPose_t pose = Pose();
		VRServerDriverHost()->TrackedDevicePoseUpdated(m_id, pose, sizeof(pose));
		if (!active)
			return;
		VRDriverInput()->UpdateScalarComponent(m_trigger, s.trigger, 0);
		VRDriverInput()->UpdateScalarComponent(m_grip, s.grip, 0);
		VRDriverInput()->UpdateBooleanComponent(m_trigger_click, (s.buttons & VPEN_BTN_TRIGGER_CLICK) != 0, 0);
		VRDriverInput()->UpdateBooleanComponent(m_grip_click, (s.buttons & VPEN_BTN_GRIP_CLICK) != 0, 0);
		VRDriverInput()->UpdateBooleanComponent(m_menu, (s.buttons & VPEN_BTN_MENU) != 0, 0);
		VRDriverInput()->UpdateBooleanComponent(m_system, (s.buttons & VPEN_BTN_SYSTEM) != 0, 0);
	}

	const char *Serial() const { return m_serial; }
	int Slot() const { return m_slot; }
	PropertyContainerHandle_t Container() const {
		return m_id == k_unTrackedDeviceIndexInvalid ? k_ulInvalidPropertyContainer
				: VRProperties()->TrackedDeviceToPropertyContainer(m_id);
	}

private:
	int m_slot;
	const vpen_shared *m_shm;
	uint32_t m_id = k_unTrackedDeviceIndexInvalid;
	char m_serial[32];
	VRInputComponentHandle_t m_trigger = 0, m_grip = 0;
	VRInputComponentHandle_t m_trigger_click = 0, m_grip_click = 0, m_menu = 0, m_system = 0;
	VRInputComponentHandle_t m_haptic = 0;
};

class CServerDriver : public IServerTrackedDeviceProvider {
public:
	EVRInitError Init(IVRDriverContext *ctx) override {
		VR_INIT_SERVER_DRIVER_CONTEXT(ctx);
		m_shm = (vpen_shared *)vpen_shm_map(sizeof(vpen_shared));
		if (m_shm && (m_shm->magic != VPEN_MAGIC || m_shm->version != VPEN_VERSION)) {
			// First mapping, or a file from another vpen_shm version: stamp the header for the feeder.
			std::memset(m_shm, 0, sizeof(vpen_shared));
			m_shm->magic = VPEN_MAGIC;
			m_shm->version = VPEN_VERSION;
		}
		int pens = VRSettings() ? VRSettings()->GetInt32("driver_vpen", "pens", nullptr) : 0;
		if (pens <= 0 || pens > VPEN_MAX)
			pens = 4;
		m_count = pens;
		for (int i = 0; i < m_count; i++) {
			m_pen[i] = new CPenDevice(i, m_shm);
			VRServerDriverHost()->TrackedDeviceAdded(m_pen[i]->Serial(),
					TrackedDeviceClass_Controller, m_pen[i]);
		}
		char msg[64];
		std::snprintf(msg, sizeof(msg), "vpen: %d Quest 3 Touch Plus controllers added, shm %s", m_count, m_shm ? "mapped" : "FAILED");
		log(msg);
		return VRInitError_None;
	}

	void Cleanup() override {
		for (int i = 0; i < m_count; i++) {
			delete m_pen[i];
			m_pen[i] = nullptr;
		}
		vpen_shm_unmap(m_shm, sizeof(vpen_shared));
		m_shm = nullptr;
		VR_CLEANUP_SERVER_DRIVER_CONTEXT();
	}

	const char *const *GetInterfaceVersions() override { return k_InterfaceVersions; }

	void RunFrame() override {
		PollHaptics();
		if (!m_shm)
			return;
		// seqlock read: retry while the writer holds it (odd) or it moves under us.
		vpen_shared snap;
		for (int tries = 0; tries < 8; tries++) {
			uint64_t s0 = __atomic_load_n(&m_shm->seq, __ATOMIC_ACQUIRE);
			if (s0 & 1)
				continue;
			std::memcpy(&snap, (const void *)m_shm, sizeof(snap));
			uint64_t s1 = __atomic_load_n(&m_shm->seq, __ATOMIC_ACQUIRE);
			if (s0 == s1)
				break;
		}
		for (int i = 0; i < m_count; i++) {
			bool active = (uint32_t)i < snap.count;
			m_pen[i]->Update(snap.pen[i], active);
		}
	}
	// A haptic pulse an app sends to a controller bumps its slot's haptic_seq for the feeder.
	void PollHaptics() {
		VREvent_t ev;
		while (VRServerDriverHost()->PollNextEvent(&ev, sizeof(ev))) {
			if (ev.eventType != VREvent_Input_HapticVibration || !m_shm)
				continue;
			for (int i = 0; i < m_count; i++) {
				if (m_pen[i]->Container() == ev.data.hapticVibration.containerHandle)
					__atomic_add_fetch(&m_shm->pen[i].haptic_seq, 1, __ATOMIC_RELEASE);
			}
		}
	}

	bool ShouldBlockStandbyMode() override { return false; }
	void EnterStandby() override {}
	void LeaveStandby() override {}

private:
	vpen_shared *m_shm = nullptr;
	int m_count = 0;
	CPenDevice *m_pen[VPEN_MAX] = {};
};

static CServerDriver g_server;

#ifdef _WIN32
#define VPEN_EXPORT __declspec(dllexport)
#else
#define VPEN_EXPORT __attribute__((visibility("default")))
#endif

extern "C" VPEN_EXPORT void *
HmdDriverFactory(const char *pInterfaceName, int *pReturnCode) {
	if (pInterfaceName && std::strcmp(pInterfaceName, IServerTrackedDeviceProvider_Version) == 0)
		return &g_server;
	if (pReturnCode)
		*pReturnCode = VRInitError_Init_InterfaceNotFound;
	return nullptr;
}
